version: '3.9'

services:
  service-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=service-app
    container_name: service-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - POSTGRES_HOST=${POSTGRES_CONTAINER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_URL=${POSTGRES_CONTAINER_URL}
    depends_on:
      - postgres
      - redis
      - prometheus

  # worker-app:
  #   image: ./

  postgres:
    image: postgres:13.13-bullseye
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-bookworm
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    restart: always
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - prometheus_data:/prometheus

  pushgateway:
    image: prom/pushgateway:v1.7.0
    container_name: pushgateway
    restart: always
    ports:
      - ${PUSHGATEWAY_PORT}:${PUSHGATEWAY_PORT}

volumes:
  postgres_data: {}
  redis_data: {}
  prometheus_data: {}
