version: '3.9'

services:
  service-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-app
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - POSTGRES_HOST=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - postgres
      - redis

  worker-app:
    image: ./

  postgres:
    image: postgres:13.13-bullseye
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

  redis:
    image: redis:7.2.4-bookworm
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - local_network

  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    restart: always
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - prometheus_data:/prometheus
    networks:
      - local_network

volumes:
  postgres_data: {}
  redis_data: {}
  prometheus_data: {}

networks:
  local_network:
    driver: bridge
