version: '3'

tasks:
  cs:
    cmds:
      - colima start --arch linux/amd64

  cr:
    cmds:
      - colima restart

  ds:
    deps: [cs]
    cmds:
      - docker stop {{.CLI_ARGS}}

  dsa:
    deps: [cs]
    cmds:
      - docker ps -q | xargs -r docker stop

  dp:
    deps: [cs, dsa]
    cmds:
      - docker system prune -af --volumes

  dup:
    deps: [cs]
    cmds:
      - docker compose up -d

  dls:
    deps: [cs]
    cmds:
      - docker container ls -a

  dbup:
    deps: [cs]
    cmds:
      - DOCKER_BUILDKIT=0 docker compose up -d

  dd:
    deps: [cs]
    cmds:
      - docker run --rm -it {{.CLI_ARGS}} sh
